// <auto-generated />
using System;
using Jellyfin.Plugin.AetherAnalysis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jellyfin.Plugin.AetherAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260716140016_ProductionBaseline")]
    partial class ProductionBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Jellyfin.Plugin.AetherAnalysis.Infrastructure.AnalysisMaintenanceState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastCapacityDeletedRecords")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastCompletedAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastDeletedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastRetentionDeletedRecords")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("analysis_maintenance_state", (string)null);
                });

            modelBuilder.Entity("Jellyfin.Plugin.AetherAnalysis.Infrastructure.AnalysisRecord", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaSourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CompressedDocument")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("CreatedAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintQuality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessedAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaFingerprint")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredAtUnixTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UncompressedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "MediaSourceId", "AlgorithmId", "AlgorithmVersion");

                    b.HasIndex("LastAccessedAtUnixTimeMilliseconds");

                    b.HasIndex("StoredAtUnixTimeMilliseconds");

                    b.ToTable("analysis_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
