version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet-patches:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
